### ISSUE TITLE
Getting type mismatch: got <TomlTableRef> when using pairs on table object

### ISSUE THREAD

**Issue by kaushalmodi** [NimParsers/parsetoml#11]
Hello,

Here is my nim version:

```
Nim Compiler Version 0.18.1 [Linux: amd64]
Compiled at 2018-05-10 14:18:58
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 9048bcc54b5fe8d0ae8c24b9cf7454cfa897ce5a
active boot switches: -d:release
```

Here is a simple test case I constructed using this module's docs:

```nim
import parsetoml, json

let table1 = parsetoml.parseString("""
[input]
file_name = "test.txt"

[output]
verbose = true
""")
echo table1.toJson.pretty

# http://parsetoml.readthedocs.io/en/latest/access.html#tree-traversal
from strutils import spaces
proc dump*(table : TomlTableRef, indentLevel : int = 0) =
  let space = spaces(indentLevel)
  for key, val in pairs(table):
    if val.kind == TomlValueKind.Table:
      echo space & key & " = table"
      dump(val.tableVal, indentLevel + 4)
    elif (val.kind == TomlValueKind.Array and
          val.arrayVal[0].kind == TomlValueKind.Table):
      for idx, val in val.arrayVal:
        echo space & key & "[" & $idx & "] = table"
        dump(val.tableVal, indentLevel + 4)
    else:
      echo space & key & " = " & $(val[])

dump(table1)
```

But I get this error as it looks like `pairs` does not support `TomlTableRef` type:

```
Hint: test2 [Processing]
Hint: math [Processing]
Hint: streams [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: algorithm [Processing]
Hint: tables [Processing]
Hint: hashes [Processing]
Hint: unicode [Processing]
Hint: json [Processing]
Hint: lexbase [Processing]
Hint: macros [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: sequtils [Processing]
test2.nim(16, 24) Error: type mismatch: got <TomlTableRef>
but expected one of:
iterator pairs[T](a: openArray[T]): tuple[key: int, val: T]
iterator pairs[T](a: seq[T]): tuple[key: int, val: T]
iterator pairs(a: string): tuple[key: int, val: char]
iterator pairs[IX, T](a: array[IX, T]): tuple[key: IX, val: T]
iterator pairs(a: cstring): tuple[key: int, val: char]
iterator pairs(node: JsonNode): tuple[key: string, val: JsonNode]

expression: pairs(table)
```

---

I ended up in this debug because I have a config.toml file like below that I need to parse:

```toml
[tmux]
  req_env_vars = ["STOW_PKGS_TARGET"]
  [tmux.set_env_vars]
    CFLAGS = "-fgnu89-inline -I${STOW_PKGS_TARGET}/include -I${STOW_PKGS_TARGET}/include/ncursesw"
    LDFLAGS = "-L${STOW_PKGS_TARGET}/lib"
```

I am reading it using:

```nim
let
  configFile = getConfigDir() / "nbuild" / "config.toml" # ~/.config/nbuild/config.toml

...

# later in a proc
let cfg = parsetoml.parseFile(configFile)
dump(cfg)
```

I basically want to check if the table object contains a key named "tmux".. I want to eventually do something like (pseudocode follows):

```nim
if (parsetoml.keyExists(cfg, "tmux")):
  # do tmux specific things
```

**Comment by ziotom78** [comment]
Hi @kaushalmodi , thanks a lot for the report. I am no longer interested in Nim, but I would be happy to merge any PR which can fix this problem!

**Comment by data-man** [comment]
@kaushalmodi
Why you wrote your own dump proc? There is dump [parsetoml.nim#L1018](https://github.com/ziotom78/parsetoml/blob/master/parsetoml.nim#L1018)

As solution your issue just add ```tables``` to imported modules.

**Comment by data-man** [comment]
@ziotom78

Can we create the new NimParsers organization and move your repository to a new address?

**Comment by kaushalmodi** [comment]
>  I am no longer interested in Nim

Oh no :( This looks like a great project though.

As @data-man suggests, if you can move it to an organization so that it gets routinely maintained by an active Nim developer, so that this package does die silently.. it would be a big loss.

**Comment by kaushalmodi** [comment]
> Why you wrote your own dump proc? 

I misinterpreted [this piece in the documentation][1].. I thought that snippet was for users to try.

> There is dump parsetoml.nim#L1018

I figured that out later :)


> As solution your issue just add tables to imported modules.

Thank you! I could have never guessed that that module was needed for that.

[1]: http://parsetoml.readthedocs.io/en/latest/access.html#tree-traversal
