### ISSUE TITLE
Move this repo to an Organization

### ISSUE THREAD

**Issue by kaushalmodi** [NimParsers/parsetoml#12]
From @ziotom78's comment [here][1]:

> I am no longer interested in Nim, but I would be happy to merge any PR which can fix this problem!

:(

From @data-man's comment [here][2]:

> Can we create the new NimParsers organization and move your repository to a new address?

Copying @dom96, @Araq.

[1]: https://github.com/ziotom78/parsetoml/issues/11#issuecomment-389923082
[2]: https://github.com/ziotom78/parsetoml/issues/11#issuecomment-389930159

**Comment by ziotom78** [comment]
Sure, no problem! But it's not clear to me how to do it. I hope that the operation will be quite easy to do, as at the moment I am really busy…

**Comment by dom96** [comment]
Shouod be easy to do. Someone just has to create the organisation and add
@ziotom78 to it. Transferring the repo is then just the click of a button :)

**Comment by kaushalmodi** [comment]
@ziotom78 I just created the NimParsers organization, and have included everyone involved to it. 

Interestingly, your parsetoml repo showed up there right away: https://github.com/NimParsers/parsetoml

Pending steps:

- [x] https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization
- [ ] Change the repo location in nimble database? @dom96

**Comment by ziotom78** [comment]
> Interestingly, your parsetoml repo showed up there right away: https://github.com/NimParsers/parsetoml

No, it was me who transferred the repository in NimParsers. So, I believe that step 1 is done :-)

**Comment by data-man** [comment]
Can be closed.

**Comment by data-man** [comment]
Give me rights for this! :smile:

**Comment by kaushalmodi** [comment]
> Give me rights for this! 

I've added you to the NimParsers organization. So I thought that would take care of that. I'll take a look at this better when I get to a computer.

**Comment by data-man** [comment]
@kaushalmodi 

Also add @PMunch to the collaborators, please.

**Comment by kaushalmodi** [comment]
I had invited him as I saw that he recently refactored this package almost entirely. Just waiting for him to accept :)

**Comment by PMunch** [comment]
Wait really? I accepted the invite to join the organisation, haven't seen another one. Where do I go to accept this?

**Comment by data-man** [comment]
@kaushalmodi
https://github.com/orgs/NimParsers/people :smile:

But the collaborators and the members are different things.
