### ISSUE TITLE
Need help retrieving all the keys in a TOML table and reading string arrays

### ISSUE THREAD

**Issue by kaushalmodi** [NimParsers/parsetoml#14]
I have this test code:

```nim
import parsetoml, tables, strformat

let
  cfg = parsetoml.parseString("""
[tmux]
  req_env_vars = ["STOW_PKGS_TARGET"]
  [tmux.set_env_vars]
    CFLAGS = "-fgnu89-inline -I${STOW_PKGS_TARGET}/include -I${STOW_PKGS_TARGET}/include/ncursesw"
    LDFLAGS = "-L${STOW_PKGS_TARGET}/lib"
""")
  pkg = "tmux"
```

1. How can I loop through all the **keys** only inside that `[tmux]` table? In actual code, I wouldn't use the hard-coded value `"tmux"`; I would use that `pkg` variable.
2. Once I get to the `req_env_vars` key in the `pkg` table, how do I retrieve the list of strings?

Sorry, I have been trying a lot of different things, read through the `parsetoml` docs, but cannot figure this out.

**Comment by kaushalmodi** [comment]
Was able to figure out this one..

> Once I get to the req_env_vars key in the pkg table, how do I retrieve the list of strings?

```nim
echo cfg.getStringArray(fmt"{pkg}.req_env_vars")
```

*Now I need to programmatically derive the `req_env_vars` portion.. which is the question no. 1 in my above post.*

**Comment by ziotom78** [comment]
Hard to say for sure, as it has been a long time since I used this library. However, it seems to me that the implementation of the `dump` procedure (see [here](http://parsetoml.readthedocs.io/en/latest/access.html#tree-traversal) for a reference in the manual) might help you in finding the solution.

**Comment by PMunch** [comment]
Something like this perhaps:
```
import parsetoml, tables, strformat

let
  cfg = parsetoml.parseString("""
[tmux]
  req_env_vars = ["STOW_PKGS_TARGET"]
  [tmux.set_env_vars]
    CFLAGS = "-fgnu89-inline -I${STOW_PKGS_TARGET}/include -I${STOW_PKGS_TARGET}/include/ncursesw"
    LDFLAGS = "-L${STOW_PKGS_TARGET}/lib"
""")
  pkg = "tmux"

for key, val in cfg.pairs:
  if key == "tmux":
    for key, val in val.tableVal.pairs:
      echo key
```
This will print out `req_env_vars` and `set_env_vars`. Or of course if the only thing you want to get out of the table you can just grab the tmux table by itself:
```
import parsetoml, tables, strformat

let
  cfg = parsetoml.parseString("""
[tmux]
  req_env_vars = ["STOW_PKGS_TARGET"]
  [tmux.set_env_vars]
    CFLAGS = "-fgnu89-inline -I${STOW_PKGS_TARGET}/include -I${STOW_PKGS_TARGET}/include/ncursesw"
    LDFLAGS = "-L${STOW_PKGS_TARGET}/lib"
""")
  pkg = "tmux"
  tmux = cfg.getValueFromFullAddr(pkg)

for key, val in tmux.tableVal.pairs:
  echo key
```

**Comment by PMunch** [comment]
A third option now is to use the `getTable` procedure which will validate that `tmux` is actually a table and not something else.

Has this been resolved now?

**Comment by kaushalmodi** [comment]
I have been away from my computer for past 2 days.. I'll get to one tonight/tomm (EDT).. and try out your suggestions in last 2 comments. Sorry for the delay.

**Comment by kaushalmodi** [comment]
Thanks! The earlier two code snippets work great!

Though, based on doc-string of `getTable`, it looks like it's a drop-in replacement for `getValueFromFullAddr`, but with better checks.

Assuming so, I have this code:

```nim
import parsetoml, tables

let
  cfg = parsetoml.parseString("""
[tmux]
  req_env_vars = ["STOW_PKGS_TARGET"]
  [tmux.set_env_vars]
    CFLAGS = "-fgnu89-inline -I${STOW_PKGS_TARGET}/include -I${STOW_PKGS_TARGET}/include/ncursesw"
    LDFLAGS = "-L${STOW_PKGS_TARGET}/lib"
""")
  pkg = "tmux"
  tmux = cfg.getTable(pkg)

for key, val in tmux.pairs:
  echo key
```

~~But I get this error:~~

> ~~test_getTable.nim(14, 21) Error: undeclared field: 'tableVal'~~

---

**Update**: Nevermind, found my mistake (and fixed it in the above snippet). This works great!!
