### ISSUE TITLE
Document the get*Array API functions

### ISSUE THREAD

**Issue by kaushalmodi** [NimParsers/parsetoml#15]
The `getStringArray`, etc. functions need to be documented in http://parsetoml.readthedocs.io/en/latest/access.html#generic-functions

Looking at the code, these array-fetching function are defined:

```nim
defineGetArray(getIntArray, TomlValueKind.Int, intVal, int64)
defineGetArray(getFloatArray, TomlValueKind.Float, floatVal, float64)
defineGetArray(getBoolArray, TomlValueKind.Bool, boolVal, bool)
defineGetArray(getStringArray, TomlValueKind.String, stringVal, string)
defineGetArray(getDateTimeArray, TomlValueKind.DateTime,
               dateTimeVal, TomlDateTime)
```

**Comment by ziotom78** [comment]
PRs are welcome!

**Comment by PMunch** [comment]
This should be fixed as of https://github.com/NimParsers/parsetoml/commit/5105204b1b3eedc19ceb335bd576f5d2bed19c95

**Comment by PMunch** [comment]
Hmm, just realised that the documentation is not the same as the doc-comments.. We should switch to a system where these are auto-generated from the doc-comments.

**Comment by kaushalmodi** [comment]
> We should switch to a system where these are auto-generated from the doc-comments.

Done! http://nimparsers.github.io/parsetoml/

**Comment by PMunch** [comment]
Great, now just to write some proper documentation in that file
