### ISSUE TITLE
Create a more robust interface with TOML object

### ISSUE THREAD

**Issue by PMunch** [NimParsers/parsetoml#18]
With the possibility to output TOML it makes sense for people to create TOML with this package. As of https://github.com/NimParsers/parsetoml/commit/17c6c5103b5e0c56946908fa57e9ca2e2c9712f0 I've added `set` and `add` procedures for the basic types, and an iterator to array types which is able to manipulate entries. But I feel like this interface could be improved upon a lot. Maybe look at how the JSON module is handling this? Having TOML be as easy to use as JSON would greatly improve how usable this module is.

**Comment by PMunch** [comment]
Tried to copy the JSON interface in https://github.com/NimParsers/parsetoml/pull/19, thoughts?

**Comment by kaushalmodi** [comment]
@PMunch Looks like this can be closed?

**Comment by PMunch** [comment]
Yeah.. I was thinking of discussing the pros and cons of the two interfaces, but @data-man went ahead and merged it in :stuck_out_tongue: So I guess we can close this issue now.
