### ISSUE TITLE
Support TOML v0.5.0

### ISSUE THREAD

**Issue by data-man** [NimParsers/parsetoml#22]
0.5.0/2018-07-11 [was](https://github.com/toml-lang/toml/blob/master/CHANGELOG.md) released.
The changes:

- Add dotted keys.
- Add hex, octal, and binary integer formats.
- Add special float values (inf, nan)
- Rename Datetime to Offset Date-Time.
- Add Local Date-Time.
- Add Local Date.
- Add Local Time.
- Add ABNF specification.
- Allow space (instead of T) to separate date and time in Date-Time.
- Allow accidental whitespace between backslash and newline in the line continuation operator in multi-line basic strings.
- Specify that the standard file extension is .toml.
- Specify that MIME type is application/toml
- Clarify that U+007F is an escape character.
- Clarify that keys are always strings.
- Clarify that you cannot use array-of-table to append to a static array.
- Clarify that a TOML file must be a valid UTF-8 document.
- Clarify valid Array values.
- Clarify that literal strings can be table keys.
- Clarify that at least millisecond precision expected for Date-Time and Time.
- Clarify that comments are OK in multiline arrays.
- Clarify that +0, -0, +0.0, and -0.0 are valid and what they mean.

**Comment by PMunch** [comment]
I went looking for a new test-suite for TOML 0.5.0 but couldn't find any, so it's kinda hard to update and make sure everything works.

**Comment by PMunch** [comment]
[This](https://github.com/NimParsers/parsetoml/commit/e9fd05cdb7312019051e8ad8e27238a9ad1257f2) should hopefully work, it's based on Python's example 0.5.0 file which I've also put in the repo. I've also edited the official ABNF to be a bit more restrictive (which is in line with the actual spec) and tried generating some crazy test files with `abnfgen`. This actually worked pretty well and most of the issues I had was with inconsistencies with the spec.

**Comment by PMunch** [comment]
Rolled back my changes on the master branch as it wasn't passing the tests properly. I've moved the work onto a new branch which is still WIP: https://github.com/NimParsers/parsetoml/tree/0.5.0

**Comment by PMunch** [comment]
TOML 0.5.0 should now be supported as of this: https://github.com/NimParsers/parsetoml/commit/2b738e79aba8260c4f4766e7b00844c2561b8fd6
