### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by kaushalmodi** [NimParsers/parsetoml#26]
@PMunch Do you think a new release can be tagged (involves adding a new git tag and updating the version in the .nimble).

**Comment by PMunch** [comment]
Yeah sure, do you want me to do it?

**Comment by kaushalmodi** [comment]
@PMunch Yes please. I wasn't sure if there was a reason for not tagging it.

**Comment by kaushalmodi** [comment]
May be cut a new release after `toml-test` passes? https://github.com/NimParsers/parsetoml/pull/28

**Comment by PMunch** [comment]
Seems reasonable
