### ISSUE TITLE
Travis failure after test for "array of nested inline table" was added to toml_test

### ISSUE THREAD

**Issue by kaushalmodi** [NimParsers/parsetoml#30]
toml_test was updated with commit https://github.com/BurntSushi/toml-test/commit/fb8ca0652d056e4055ca4a85519a69c3283c5f61 on Nov 27.

The Travis tests for parsetoml run every week, and the next test day after Nov 27 happened to be Nov 20 when it failed: https://travis-ci.org/NimParsers/parsetoml/builds/461974298.

```
Test: nested-inline-table-array (valid)
../src/parsetoml.nim(883) parseValue
Error: unhandled exception: (1:14) unexpected character "{" [TomlError]
126 passed, 1 failed
```

/cc @PMunch

**Comment by PMunch** [comment]
The run before says "126 passed, 0 failed" while this one says "126 passed, 1 failed" so it appears a test was added for something we don't support. I'll look into it but the logic for inline arrays is pretty hairy and might need a complete rewrite to support this

**Comment by kaushalmodi** [comment]
@PMunch I meant exactly that, that the toml-test has been updated with new tests supporting a new TOML syntax.

>  I'll look into it but the logic for inline arrays is pretty hairy and might need a complete rewrite to support this

Thank you!

I am watching out for when https://github.com/BurntSushi/toml-test/pull/51 and https://github.com/BurntSushi/toml-test/pull/53 get merged in toml-test .. Those also seem to add tests for a lot of new syntax. *But our CI uses the latest toml-test. So we will be auto-notified if any update in toml-test causes tests with parsetoml to fail.*

**Comment by kaushalmodi** [comment]
Reminder: parsetoml to be reenabled in Nim ci once all tests pass; ref: https://github.com/nim-lang/Nim/commit/af6539b0c3b6958251737d5bc140cbcc8652eb8b

**Comment by PMunch** [comment]
Isn't this fixed?

**Comment by kaushalmodi** [comment]
I need to check why parsetoml was removed from Nim CI yesterday. I was lazy to just put a reminder to check that here.

**Comment by kaushalmodi** [comment]
@PMunch I see the same error today too.

Running `nimble run_toml_test` gives:

```
github.com/BurntSushi/toml-test
Test: nested-inline-table-array (valid)

/home/kmodi/sandbox/nim/parsetoml/src/parsetoml.nim(890) parseValue
Error: unhandled exception: (1:14) unexpected character "{" [TomlError]


127 passed, 1 failed
```

**Comment by PMunch** [comment]
Fixed by https://github.com/NimParsers/parsetoml/commit/988f6f5885b6715927f1beb4287eb417f2cb4832

**Comment by kaushalmodi** [comment]
@PMunch: wow! you are on a roll! Time to cut a new release of parsetoml.
