### ISSUE TITLE
[feature request] Support `.insert`, `.delete` for TOML arrays

### ISSUE THREAD

**Issue by kaushalmodi** [NimParsers/parsetoml#34]
I would find these to be useful to read TOML from a file, modify it and write it back.

The sequences have [`.insert`][1] and [`.delete`][2], but they cannot be used for the Array kind `TomlValueRef` as they technically aren't sequences.

Today, I ended up with a little application where I would like to read from a TOML file, and then update the same: http://ix.io/1RjZ/nim. If I had `insert` and `delete`, that would simplify that code a bit.

---

Thought: Is it possible to make the Array kind TomlValueRef's simply Nim sequences of TomlValueRef type? If so, all the sequence handling machinery in Nim can be directly used for those.

/cc @PMunch

---

To try out the above linked snippet from ix.io, simply compile it once and rerun the binary few times.. you will see a `config_table.toml` created/updated in the same directory each time you run the binary.

Example of the created `config_table.toml` after 5 or more runs of the compiled binary:

```
[[sync]]
datetime = "2019-08-11T12:41:08-04:00"
description = "def"

[[sync]]
datetime = "2019-08-11T12:41:01-04:00"
description = "def"

[[sync]]
datetime = "2019-08-11T12:40:52-04:00"
description = "def"

[[sync]]
datetime = "2019-08-11T12:40:51-04:00"
description = "def"

[[sync]]
datetime = "2019-08-11T12:40:49-04:00"
description = "def"
```

[1]: https://nim-lang.github.io/Nim/sequtils#insert%2Cseq%5BT%5D%5BT%5D%2CopenArray%5BT%5D%2Cint
[2]: https://nim-lang.github.io/Nim/sequtils#delete%2Cseq%5BT%5D%5BT%5D%2CNatural%2CNatural

**Comment by PMunch** [comment]
I'm not entirely sure if I understand the issue. You can access the [underlying sequence](https://github.com/NimParsers/parsetoml/blob/master/src/parsetoml.nim#L93) of a TomlValue.

**Comment by kaushalmodi** [comment]
Oh, I see. Thanks. 

I was suggesting addition of sugar syntax for delete and insert like you have for add:

https://github.com/NimParsers/parsetoml/blob/1f824d481278ac38e3a37d8714b5d405224152fe/src/parsetoml.nim#L1571

**Comment by kaushalmodi** [comment]
@PMunch That's for your tip. With that, this works exactly as I wanted: http://ix.io/1RqE/nim.

```diff
--- update_toml_table_file_v1.nim       2019-08-12 13:06:13.984494000 -0400
+++ update_toml_table_file.nim  2019-08-12 13:05:03.794752000 -0400
@@ -1,4 +1,4 @@
-import std/[os, strformat, times, strutils]
+import std/[os, strformat, times, sequtils]
 import parsetoml

 type
@@ -17,31 +17,25 @@
 echo &"Current datetime: {currentDateTimeStr}"

 var
-  cfgCurrent: TomlValueRef
-  cfgNumSync = 0
+  cfg: TomlValueRef

 if fileExists(tomlFile):
-  cfgCurrent = parsetoml.parseFile(tomlFile)
-  if cfgCurrent.hasKey(arrKey):
-    cfgNumSync = cfgCurrent[arrKey].len
-  echo &"cfgCurrent (of type {$type(cfgCurrent)}) = `{cfgCurrent}'"
-echo &"cfgNumSync = {cfgNumSync}"
-
-var
-  cfgUpdated = parsetoml.parseString("") # Initialize an empty TOML object
-cfgUpdated[arrKey] = newTArray() # Initialize an empty TOML array indexed by arrKey key
+  cfg = parsetoml.parseFile(tomlFile)
+  echo &"cfg (of type {$type(cfg)}) = `{cfg}'"
+else:
+  cfg = parsetoml.parseString("") # Initialize an empty TOML object
+  cfg[arrKey] = newTArray() # Initialize an empty TOML array indexed by arrKey key

 # Put the new element at the beginning of the TOML Array.
 let
   newElem = SyncInfo(datetime: currentDateTimeStr, description: "def")
-cfgUpdated[arrKey].add(?newElem)
+cfg[arrKey].arrayVal.insert(?newElem)

-# Append old TOML array elements, if any, after the newly added element.
-for i in 0 ..< maxElems-1: # Ensure that the num of elems in cfgUpdated[arrKey] does not exceed maxElems.
-  if i < cfgNumSync:
-    cfgUpdated[arrKey].add(cfgCurrent[arrKey][i])
+# Delete extra elements in the arrKey array, if more than maxElems.
+if cfg[arrKey].len() > maxElems:
+  cfg[arrKey].arrayVal.delete(maxElems, cfg[arrKey].len())

 # Update the TOML file.
-tomlFile.writeFile(cfgUpdated.toTomlString())
+tomlFile.writeFile(cfg.toTomlString())

 echo &"read back the updated TOML file: `{parsetoml.parseFile(tomlFile)}'"
```

Closing this issue.
