### ISSUE TITLE
getter procs default value not working

### ISSUE THREAD

**Issue by tdely** [NimParsers/parsetoml#43]
Using a getter procs default value parameter has no effect.

```
import parsetoml

let table1 = parsetoml.parseString("""
[input]
""")

let input = table1["input"]["file_name"].getStr("some_default.txt")
```

Results in `Error: unhandled exception: key not found: file_name [KeyError]`

**Comment by SolitudeSF** [comment]
it fails at `["file_name"]` not `getStr`. you have to check for key existence before accessing it.

**Comment by tdely** [comment]
Yes. But what is the point of allowing a default value if that default value cannot be used?
`table1["input"]["file_name"].getStr("some_default.txt")` is meant to return the value of "file_name" if it exists else return "some_default.txt". It is not meant to, nor does it currently, get the value of a key "some_default.txt" under the key "file_name".

**Comment by SolitudeSF** [comment]
thats not what getWhatever procs are used for. getStr will return you the string even if node you're calling it on isn't.

**Comment by SolitudeSF** [comment]
thats not what getWhatever procs are used for. getStr will return you the string even if node you're calling it on isn't.

**Comment by tdely** [comment]
It is a use case stated in the documentation of the getStr proc:
```Returns ``default`` if ``n`` is not a ``TomlValueKind.String``, or if ``n`` is nil.```

**Comment by SolitudeSF** [comment]
yes, if you call it on nil TomlValueRef it will give you default, but you dont do that in your snippet. you just trying to access the key that isnt in the table. getStr isnt called at all.

**Comment by ghost** [comment]
@tdely you should use https://github.com/NimParsers/parsetoml/blob/master/src/parsetoml.nim#L1847 if you know that a field might not exist, like this:
```nim
import parsetoml

let table1 = parsetoml.parseString("""
[input]
""")

let input = table1{"input", "file_name"}.getStr("some_default.txt")
echo input
```

This is the same behaviour as with stdlib's https://nim-lang.org/docs/json.html module so it's consistent.

**Comment by tdely** [comment]
@Yardanico thank you that is very helpful! Works great.

I was unfamiliar with the json module, if it shares behavior then I'll reference that modules docs.
