### ISSUE TITLE
Float parsing fails the toml-test when using Nim devel

### ISSUE THREAD

**Issue by kaushalmodi** [NimParsers/parsetoml#45]
This is the root cause of the recent failure of parsetoml tests on Travis weekly cron: https://travis-ci.org/github/NimParsers/parsetoml/builds/773550319

See https://github.com/nim-lang/Nim/issues/18182#issuecomment-855169927 .

**Comment by kaushalmodi** [comment]
@PMunch 

The `parseDecimalPart` is creating an incorrect outcome on Nim devel.

Here's a minimal reproducible example using `parsetoml`:

```nim
import std/[unittest]
import parsetoml # nimble install parsetoml

test "TOML float":
  check $("some_float = 0.123".parseString()["some_float"].getFloat()) == "0.123"
```

I dived into the code and ended up in `parseDecimalPart`:

https://github.com/NimParsers/parsetoml/blob/376086763a5327478d44a0d61c774d2352668b0c/src/parsetoml.nim#L271-L299

Here's a minimal example that shows where things are going wrong on devel:

```nim
import math, sugar

var
  invPowerOfTen = 10.0
  decimalPart: float64

for ch in ['1', '2', '3']: # 0.123
  decimalPart += (int(ch) - int('0')).float / invPowerOfTen
  dump ch
  dump decimalPart
  invPowerOfTen *= 10

doAssert $decimalPart == "0.123"
```

Output:

```
ch = 1
decimalPart = 0.1
ch = 2
decimalPart = 0.12000000000000001
ch = 3
decimalPart = 0.12300000000000001
/home/kmodi/sandbox/nim/bug_reports/t18182.nim(13) t18182
/home/kmodi/usr_local/apps/7/nim/devel/lib/system/assertions.nim(39) failedAssertImpl
/home/kmodi/usr_local/apps/7/nim/devel/lib/system/assertions.nim(29) raiseAssert
/home/kmodi/usr_local/apps/7/nim/devel/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: /home/kmodi/sandbox/nim/bug_reports/t18182.nim(13, 10) `$decimalPart == "0.123"` 
```

When I run the same code on latest Nim stable on Playground: https://play.nim-lang.org/#ix=3oMQ, the output is:

```
ch = 1
decimalPart = 0.1
ch = 2
decimalPart = 0.12
ch = 3
decimalPart = 0.123
```

These is how far I could get. I don't understand the low level details on why the outcome is different. Also copying @timotheecour in case he's interested in helping fix this in parsetoml.

**Comment by kaushalmodi** [comment]
OK, so this fails on devel:

```
nim --eval:'assert 0.1 + 0.02 == 0.12'
```

I am still not sure if this is something that should be fixed in Nim devel. But assuming it's not, can something like this be done in parsetoml:

```
nim --eval:'assert (10 + 2)/100.0 == 0.12'
```

Above passes. So we first need to figure out how many decimal point digits we have, scale up the decimal parts and then normalize using a float division.

---

Or somehow `strutils.parseFloat` needs to be used as suggested in https://github.com/nim-lang/Nim/issues/18182#issuecomment-855168337 so that it does the Right Thing.

**Comment by timotheecour** [comment]
> OK, so this fails on devel:
> nim --eval:'assert 0.1 + 0.02 == 0.12'

not just nim devel, 1.4.4 too, and indeed, 0.1 + 0.02 != 0.12 with FP semantics.

> Or somehow strutils.parseFloat

`parseutils.parseFloat` is IMO what should be used
