### ISSUE TITLE
Support TOML 0.4.0

### ISSUE THREAD

**Issue by ziotom78** [NimParsers/parsetoml#5]
A new version of the TOML specification has appeared: https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md, with some nice additions (use of underscores to improve the readability of numbers, inline tables, …). It shouldn't be too hard to support these.

**Comment by PMunch** [comment]
Added support for v0.4.0 in #9 along with making sure that everything passes the validation suite at https://github.com/BurntSushi/toml-test
