### ISSUE TITLE
Error: '==' can have side effects

### ISSUE THREAD

**Issue by prashanth-hegde** [NimParsers/parsetoml#60]
## Description

In Nim 1.9.1, just importing `parsetoml` library fails to compile code with the below error. With the impending Nim2.0 release, this may break backward compatibility.

```
/Users/Z002DCM/.nimble/pkgs2/parsetoml-0.6.0-9adcce9012c4243954da393333ee8ec243e20aab/parsetoml.nim(1745, 27) template/generic instantiation of `==` from here
/Users/Z002DCM/apps/nim/lib/system/comparisons.nim(309, 6) Error: '==' can have side effects
> /Users/Z002DCM/apps/nim/lib/system/comparisons.nim(334, 13) Hint: '==' calls `.sideEffect` '=='
>> /Users/Z002DCM/.nimble/pkgs2/parsetoml-0.6.0-9adcce9012c4243954da393333ee8ec243e20aab/parsetoml.nim(1725, 6) Hint: '==' called by '=='
```

## Steps to Reproduce: 

1. clone nim from git devel branch `git clone https://github.com/nim-lang/Nim.git`
2. create a simple project 
3. import `parsetoml` into any file
4. compile and/or run

**Comment by Vindaar** [comment]
I was just about to open an issue for this as well. While checking out the repository to try to fix it myself I noticed that it's already fixed on #head. Could one of you @PMunch or @kaushalmodi (or someone else with write access) push a new version?

**Comment by kaushalmodi** [comment]
@Vindaar I am without computer access until Jan 8. But I was able to add you as a maintainer to this repo. Can you please tag a new release? 

Thank you for helping with maintenance of this package.

**Comment by PMunch** [comment]
I'm offline until tomorrow (mostly) but if it's not done by then I'll tag a new release

**Comment by Vindaar** [comment]
Thanks to both of you!

I pushed an update to the nimble file and tagged version `v0.7.0`. I kept it in line with the previous major bumps instead of bumping to a patch version.
