### ISSUE TITLE
can no longer compile with `strictFuncs`

### ISSUE THREAD

**Issue by ee7** [NimParsers/parsetoml#61]
### Current behavior

We cannot compile with `--experimental:strictFuncs`:

```console
$ nim c --experimental:strictFuncs src/parsetoml.nim
/tmp/parsetoml/src/parsetoml.nim(1742, 6) Error: '==' can have side effects
> /tmp/parsetoml/src/parsetoml.nim(1769, 22) Hint: '==' calls `.sideEffect` '[]'
>> /foo/nim-devel/lib/pure/collections/tables.nim(1851, 6) Hint: '[]' called by '=='
```

### Expected behavior

Compilation succeeds.

### Details

Nim 1.6.0 [added](https://nim-lang.org/blog/2021/10/19/version-160-released.html#strict-effects) `--experimental:strictEffects`. But in devel Nim, `strictEffects` is the default, and `--legacy:laxEffects` is available to opt-in to the legacy behavior.

Before https://github.com/NimParsers/parsetoml/commit/bb903611e91584efd03b7327493ade0859eeddea (#58), the latest devel Nim can compile parsetoml with or without `strictFuncs`, as long as it uses `laxEffects`:

```console
$ git checkout 609e03e
HEAD is now at 609e03e make TOML empty arrays work, add test
$ nim c src/parsetoml.nim
/tmp/parsetoml/src/parsetoml.nim(1762, 27) template/generic instantiation of `==` from here
/foo/nim-devel/lib/system/comparisons.nim(309, 6) Error: '==' can have side effects
> /foo/nim-devel/lib/system/comparisons.nim(334, 13) Hint: '==' calls `.sideEffect` '=='
>> /tmp/parsetoml/src/parsetoml.nim(1742, 6) Hint: '==' called by '=='
$ nim c --legacy:laxEffects src/parsetoml.nim
62096 lines; 1.234s; 88.59MiB peakmem; proj: /tmp/parsetoml/src/parsetoml.nim; out: /tmp/parsetoml/src/parsetoml [SuccessX]
$ nim c --legacy:laxEffects --experimental:strictFuncs src/parsetoml.nim
62096 lines; 1.234s; 88.59MiB peakmem; proj: /tmp/parsetoml/src/parsetoml.nim; out: /tmp/parsetoml/src/parsetoml [SuccessX]
```

With https://github.com/NimParsers/parsetoml/commit/bb903611e91584efd03b7327493ade0859eeddea, the latest devel Nim can compile parsetoml with strictEffects (that is, without `laxEffects`), but it can no longer compile with `strictFuncs`:

```console
$ git checkout bb90361
Previous HEAD position was 609e03e make TOML empty arrays work, add test
HEAD is now at bb90361 patches for strict effects (#58)
$ nim c src/parsetoml.nim
62096 lines; 1.134s; 88.59MiB peakmem; proj: /tmp/parsetoml/src/parsetoml; out: /tmp/parsetoml/src/parsetoml [SuccessX]
$ nim c --experimental:strictFuncs src/parsetoml.nim
/tmp/parsetoml/src/parsetoml.nim(1742, 6) Error: '==' can have side effects
> /tmp/parsetoml/src/parsetoml.nim(1769, 22) Hint: '==' calls `.sideEffect` '[]'
>> /foo/nim-devel/lib/pure/collections/tables.nim(1851, 6) Hint: '[]' called by '=='
```

@ringabout any thoughts on how we should resolve the above?

The relevant lines are here:

https://github.com/NimParsers/parsetoml/blob/bb903611e91584efd03b7327493ade0859eeddea/src/parsetoml.nim#L1763-L1770

and [here](https://github.com/nim-lang/Nim/blob/a8718d8a9e1aba7df55b1a3df1ce48a3f4f62bff/lib/pure/collections/tables.nim#L1851-L1872) in `tables.nim`.

### Nim version

Latest devel.

```
$ nim --version
Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-05-25
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a8718d8a9e1aba7df55b1a3df1ce48a3f4f62bff
active boot switches: -d:release
```

**Comment by PMunch** [comment]
I believe this is caused by `[]` for `OrderedTableRef` dereferences the table to do the lookup, apparently this is considered to have a side-effect. Not entirely sure why this is considered a side-effect though, as it's passed in as an argument and only performs an action without side-effects..

**Comment by ee7** [comment]
I should've mentioned: the definiton of `strictFuncs` [changed](https://forum.nim-lang.org/t/9716) since @ringabout's PR. Nowaways with `strictFuncs`, the definition of a side effect includes "storing to the heap via a `ref` or `ptr` indirection".

So I guess we want to add some more `noSideEffect` overrides in `tables.nim`?

**Comment by PMunch** [comment]
It's strange though, the `[]` accessor in tables shouldn't count as a side effect as it doesn't store anything to the heap.. It might be a pessimistic thing where simply dereferencing a reference leads to it being detected as a side effect, but I'm not sure.

**Comment by ee7** [comment]
If the write tracking doesn't verify that there's no later write, maybe it's because the `[]` proc for `TableRef` and `OrderedTableRef` returns a `var` type.
