### ISSUE TITLE
missing git tag for 0.7.1

### ISSUE THREAD

**Issue by ee7** [NimParsers/parsetoml#63]
### Situation

Write

> requires "parsetoml"

in a .nimble file and run `nimble build` or `nimble lock`.

### Expected behavior

Nimble uses parsetoml version https://github.com/NimParsers/parsetoml/commit/6e5e16179fa2db60f2f37d8b1af4128aaa9c8aaf, which bumped the parsetoml version in its nimble file to 0.7.1.

### Actual behavior

Nimble uses parsetoml version 0.7.0.

### Solution

Commit https://github.com/NimParsers/parsetoml/commit/6e5e16179fa2db60f2f37d8b1af4128aaa9c8aaf was not tagged (see https://github.com/NimParsers/parsetoml/tags). Can we please tag it as 0.7.1?

**Comment by PMunch** [comment]
Fixed, thanks for reminding me

**Comment by ee7** [comment]
Thanks!
